export const TYPES = {
    CategoryService: Symbol.for('CategoryService'),
    CategoryRepository: Symbol.for('CategoryRepository'),
    StoreRepository: Symbol.for('StoreRepository'),
    StoreService: Symbol.for('StoreService'),
    ProductService: Symbol.for('ProductService'),
    ProductRepository: Symbol.for('ProductRepository'),
    HomeRepository: Symbol.for('HomeRepository'),
    HomeService: Symbol.for('HomeService'),
    CookiesService: Symbol.for('CookiesService'),
    CookiesRepository: Symbol.for('CookiesRepository'),
    BoxService: Symbol.for('BoxService'),
    BoxRepository: Symbol.for('BoxRepository'),
    CartService: Symbol.for('CartService'),
    CartRepository: Symbol.for('CartRepository'),
    AccountService: Symbol.for('AccountService'),
    AccountRepository: Symbol.for('AccountRepository'),
    StaffService: Symbol.for('StaffService'),
    StaffRepository: Symbol.for('StaffRepository'),
    OrderService: Symbol.for('OrderService'),
    OrderRepository: Symbol.for('OrderRepository')
}