'use client'
import Image from 'next/image';
export const avaiableCountries = [
    {
        code: "us",
        code3: "USA",
        name: "United States of America",
        numeric: "840",
        icon:
            <Image
                src="https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/us.svg"
                height={25}
                width={25}
                alt=''
            />,
    },
    {
        code: "ca",
        code3: "CAN",
        name: "Canada",
        numeric: "124",
        icon:
            <Image
                src="https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ca.svg"
                height={25}
                width={25}
                alt=''
            />,
    },
    {
        code: "ph",
        code3: "PHL",
        name: "Philippines",
        numeric: "608",
        icon:
            <Image
                src="https://cdn.jsdelivr.net/gh/hampusborgos/country-flags@main/svg/ph.svg"
                height={25}
                width={25}
                alt=''
            />
        ,
    },
];

export const Countries = [
    {
        "code": "AF",
        "code3": "AFG",
        "name": "Afghanistan",
        "numeric": "004",
        "dialCode": "+93",
    },
    {
        "code": "AX",
        "name": "Aland Islands",
        "dialCode": "+358",
    },
    {
        "code": "AL",
        "code3": "ALB",
        "name": "Albania",
        "numeric": "008",
        "dialCode": "+355",
    },
    {
        "code": "DZ",
        "code3": "DZA",
        "name": "Algeria",
        "numeric": "012",
        "dialCode": "+213",
    },
    {
        "code": "AS",
        "code3": "ASM",
        "name": "American Samoa",
        "numeric": "016",
        "dialCode": "+1684",
    },
    {
        "code": "AD",
        "code3": "AND",
        "name": "Andorra",
        "numeric": "020",
        "dialCode": "+376",
    },
    {
        "code": "AO",
        "code3": "AGO",
        "name": "Angola",
        "numeric": "024",
        "dialCode": "+376",
    },
    { "code": "AI", "code3": "AIA", "name": "Anguilla", "numeric": "660" },
    { "code": "AQ", "code3": "ATA", "name": "Antarctica", "numeric": "010" },
    { "code": "AG", "code3": "ATG", "name": "Antigua and Barbuda", "numeric": "028" },
    { "code": "AR", "code3": "ARG", "name": "Argentina", "numeric": "032" },
    { "code": "AM", "code3": "ARM", "name": "Armenia", "numeric": "051" },
    { "code": "AW", "code3": "ABW", "name": "Aruba", "numeric": "533" },
    { "code": "AU", "code3": "AUS", "name": "Australia", "numeric": "036" },
    { "code": "AT", "code3": "AUT", "name": "Austria", "numeric": "040" },
    { "code": "AZ", "code3": "AZE", "name": "Azerbaijan", "numeric": "031" },
    { "code": "BS", "code3": "BHS", "name": "Bahamas", "numeric": "044" },
    { "code": "BH", "code3": "BHR", "name": "Bahrain", "numeric": "048" },
    { "code": "BD", "code3": "BGD", "name": "Bangladesh", "numeric": "050" },
    { "code": "BB", "code3": "BRB", "name": "Barbados", "numeric": "052" },
    { "code": "BY", "code3": "BLR", "name": "Belarus", "numeric": "112" },
    { "code": "BE", "code3": "BEL", "name": "Belgium", "numeric": "056" },
    { "code": "BZ", "code3": "BLZ", "name": "Belize", "numeric": "084" },
    { "code": "BJ", "code3": "BEN", "name": "Benin", "numeric": "204" },
    { "code": "BM", "code3": "BMU", "name": "Bermuda", "numeric": "060" },
    { "code": "BT", "code3": "BTN", "name": "Bhutan", "numeric": "064" },
    { "code": "BO", "code3": "BOL", "name": "Bolivia (Plurinational State of)", "numeric": "068" },
    { "code": "BQ", "code3": "BES", "name": "Bonaire, Sint Eustatius and Saba", "numeric": "535" },
    { "code": "BA", "code3": "BIH", "name": "Bosnia and Herzegovina", "numeric": "070" },
    { "code": "BW", "code3": "BWA", "name": "Botswana", "numeric": "072" },
    { "code": "BV", "code3": "BVT", "name": "Bouvet Island", "numeric": "074" },
    { "code": "BR", "code3": "BRA", "name": "Brazil", "numeric": "076" },
    { "code": "IO", "code3": "IOT", "name": "British Indian Ocean Territory", "numeric": "086" },
    { "code": "BN", "code3": "BRN", "name": "Brunei Darussalam", "numeric": "096" },
    { "code": "BG", "code3": "BGR", "name": "Bulgaria", "numeric": "100" },
    { "code": "BF", "code3": "BFA", "name": "Burkina Faso", "numeric": "854" },
    { "code": "BI", "code3": "BDI", "name": "Burundi", "numeric": "108" },
    { "code": "CV", "code3": "CPV", "name": "Cabo Verde", "numeric": "132" },
    { "code": "KH", "code3": "KHM", "name": "Cambodia", "numeric": "116" },
    { "code": "CM", "code3": "CMR", "name": "Cameroon", "numeric": "120" },
    { "code": "CA", "code3": "CAN", "name": "Canada", "numeric": "124" },
    { "code": "KY", "code3": "CYM", "name": "Cayman Islands", "numeric": "136" },
    { "code": "CF", "code3": "CAF", "name": "Central African Republic", "numeric": "140" },
    { "code": "TD", "code3": "TCD", "name": "Chad", "numeric": "148" },
    { "code": "CL", "code3": "CHL", "name": "Chile", "numeric": "152" },
    { "code": "CN", "code3": "CHN", "name": "China", "numeric": "156" },
    { "code": "CX", "code3": "CXR", "name": "Christmas Island", "numeric": "162" },
    { "code": "CC", "code3": "CCK", "name": "Cocos (Keeling) Islands", "numeric": "166" },
    { "code": "CO", "code3": "COL", "name": "Colombia", "numeric": "170" },
    { "code": "KM", "code3": "COM", "name": "Comoros", "numeric": "174" },
    { "code": "CD", "code3": "COD", "name": "Congo (the Democratic Republic of the)", "numeric": "180" },
    { "code": "CG", "code3": "COG", "name": "Congo", "numeric": "178" },
    { "code": "CK", "code3": "COK", "name": "Cook Islands", "numeric": "184" },
    { "code": "CR", "code3": "CRI", "name": "Costa Rica", "numeric": "188" },
    { "code": "HR", "code3": "HRV", "name": "Croatia", "numeric": "191" },
    { "code": "CU", "code3": "CUB", "name": "Cuba", "numeric": "192" },
    { "code": "CW", "code3": "CUW", "name": "Curaçao", "numeric": "531" },
    { "code": "CY", "code3": "CYP", "name": "Cyprus", "numeric": "196" },
    { "code": "CZ", "code3": "CZE", "name": "Czechia", "numeric": "203" },
    { "code": "CI", "code3": "CIV", "name": "Côte d'Ivoire", "numeric": "384" },
    { "code": "DK", "code3": "DNK", "name": "Denmark", "numeric": "208" },
    { "code": "DJ", "code3": "DJI", "name": "Djibouti", "numeric": "262" },
    { "code": "DM", "code3": "DMA", "name": "Dominica", "numeric": "212" },
    { "code": "DO", "code3": "DOM", "name": "Dominican Republic", "numeric": "214" },
    { "code": "EC", "code3": "ECU", "name": "Ecuador", "numeric": "218" },
    { "code": "EG", "code3": "EGY", "name": "Egypt", "numeric": "818" },
    { "code": "SV", "code3": "SLV", "name": "El Salvador", "numeric": "222" },
    { "code": "GQ", "code3": "GNQ", "name": "Equatorial Guinea", "numeric": "226" },
    { "code": "ER", "code3": "ERI", "name": "Eritrea", "numeric": "232" },
    { "code": "EE", "code3": "EST", "name": "Estonia", "numeric": "233" },
    { "code": "SZ", "code3": "SWZ", "name": "Eswatini", "numeric": "748" },
    { "code": "ET", "code3": "ETH", "name": "Ethiopia", "numeric": "231" },
    { "code": "FK", "code3": "FLK", "name": "Falkland Islands [Malvinas]", "numeric": "238" },
    { "code": "FO", "code3": "FRO", "name": "Faroe Islands", "numeric": "234" },
    { "code": "FJ", "code3": "FJI", "name": "Fiji", "numeric": "242" },
    { "code": "FI", "code3": "FIN", "name": "Finland", "numeric": "246" },
    { "code": "FR", "code3": "FRA", "name": "France", "numeric": "250" },
    { "code": "GF", "code3": "GUF", "name": "French Guiana", "numeric": "254" },
    { "code": "PF", "code3": "PYF", "name": "French Polynesia", "numeric": "258" },
    { "code": "TF", "code3": "ATF", "name": "French Southern Territories", "numeric": "260" },
    { "code": "GA", "code3": "GAB", "name": "Gabon", "numeric": "266" },
    { "code": "GM", "code3": "GMB", "name": "Gambia", "numeric": "270" },
    { "code": "GE", "code3": "GEO", "name": "Georgia", "numeric": "268" },
    { "code": "DE", "code3": "DEU", "name": "Germany", "numeric": "276" },
    { "code": "GH", "code3": "GHA", "name": "Ghana", "numeric": "288" },
    { "code": "GI", "code3": "GIB", "name": "Gibraltar", "numeric": "292" },
    { "code": "GR", "code3": "GRC", "name": "Greece", "numeric": "300" },
    { "code": "GL", "code3": "GRL", "name": "Greenland", "numeric": "304" },
    { "code": "GD", "code3": "GRD", "name": "Grenada", "numeric": "308" },
    { "code": "GP", "code3": "GLP", "name": "Guadeloupe", "numeric": "312" },
    { "code": "GU", "code3": "GUM", "name": "Guam", "numeric": "316" },
    { "code": "GT", "code3": "GTM", "name": "Guatemala", "numeric": "320" },
    { "code": "GG", "code3": "GGY", "name": "Guernsey", "numeric": "831" },
    { "code": "GN", "code3": "GIN", "name": "Guinea", "numeric": "324" },
    { "code": "GW", "code3": "GNB", "name": "Guinea-Bissau", "numeric": "624" },
    { "code": "GY", "code3": "GUY", "name": "Guyana", "numeric": "328" },
    { "code": "HT", "code3": "HTI", "name": "Haiti", "numeric": "332" },
    { "code": "HM", "code3": "HMD", "name": "Heard Island and McDonald Islands", "numeric": "334" },
    { "code": "VA", "code3": "VAT", "name": "Holy See", "numeric": "336" },
    { "code": "HN", "code3": "HND", "name": "Honduras", "numeric": "340" },
    { "code": "HK", "code3": "HKG", "name": "Hong Kong", "numeric": "344" },
    { "code": "HU", "code3": "HUN", "name": "Hungary", "numeric": "348" },
    { "code": "IS", "code3": "ISL", "name": "Iceland", "numeric": "352" },
    { "code": "IN", "code3": "IND", "name": "India", "numeric": "356" },
    { "code": "ID", "code3": "IDN", "name": "Indonesia", "numeric": "360" },
    { "code": "IR", "code3": "IRN", "name": "Iran (Islamic Republic of)", "numeric": "364" },
    { "code": "IQ", "code3": "IRQ", "name": "Iraq", "numeric": "368" },
    { "code": "IE", "code3": "IRL", "name": "Ireland", "numeric": "372" },
    { "code": "IM", "code3": "IMN", "name": "Isle of Man", "numeric": "833" },
    { "code": "IL", "code3": "ISR", "name": "Israel", "numeric": "376" },
    { "code": "IT", "code3": "ITA", "name": "Italy", "numeric": "380" },
    { "code": "JM", "code3": "JAM", "name": "Jamaica", "numeric": "388" },
    { "code": "JP", "code3": "JPN", "name": "Japan", "numeric": "392" },
    { "code": "JE", "code3": "JEY", "name": "Jersey", "numeric": "832" },
    { "code": "JO", "code3": "JOR", "name": "Jordan", "numeric": "400" },
    { "code": "KZ", "code3": "KAZ", "name": "Kazakhstan", "numeric": "398" },
    { "code": "KE", "code3": "KEN", "name": "Kenya", "numeric": "404" },
    { "code": "KI", "code3": "KIR", "name": "Kiribati", "numeric": "296" },
    { "code": "KP", "code3": "PRK", "name": "Korea (the Democratic People's Republic of)", "numeric": "408" },
    { "code": "KR", "code3": "KOR", "name": "Korea (the Republic of)", "numeric": "410" },
    { "code": "KW", "code3": "KWT", "name": "Kuwait", "numeric": "414" },
    { "code": "KG", "code3": "KGZ", "name": "Kyrgyzstan", "numeric": "417" },
    { "code": "LA", "code3": "LAO", "name": "Lao People's Democratic Republic", "numeric": "418" },
    { "code": "LV", "code3": "LVA", "name": "Latvia", "numeric": "428" },
    { "code": "LB", "code3": "LBN", "name": "Lebanon", "numeric": "422" },
    { "code": "LS", "code3": "LSO", "name": "Lesotho", "numeric": "426" },
    { "code": "LR", "code3": "LBR", "name": "Liberia", "numeric": "430" },
    { "code": "LY", "code3": "LBY", "name": "Libya", "numeric": "434" },
    { "code": "LI", "code3": "LIE", "name": "Liechtenstein", "numeric": "438" },
    { "code": "LT", "code3": "LTU", "name": "Lithuania", "numeric": "440" },
    { "code": "LU", "code3": "LUX", "name": "Luxembourg", "numeric": "442" },
    { "code": "MO", "code3": "MAC", "name": "Macao", "numeric": "446" },
    { "code": "MG", "code3": "MDG", "name": "Madagascar", "numeric": "450" },
    { "code": "MW", "code3": "MWI", "name": "Malawi", "numeric": "454" },
    { "code": "MY", "code3": "MYS", "name": "Malaysia", "numeric": "458" },
    { "code": "MV", "code3": "MDV", "name": "Maldives", "numeric": "462" },
    { "code": "ML", "code3": "MLI", "name": "Mali", "numeric": "466" },
    { "code": "MT", "code3": "MLT", "name": "Malta", "numeric": "470" },
    { "code": "MH", "code3": "MHL", "name": "Marshall Islands", "numeric": "584" },
    { "code": "MQ", "code3": "MTQ", "name": "Martinique", "numeric": "474" },
    { "code": "MR", "code3": "MRT", "name": "Mauritania", "numeric": "478" },
    { "code": "MU", "code3": "MUS", "name": "Mauritius", "numeric": "480" },
    { "code": "YT", "code3": "MYT", "name": "Mayotte", "numeric": "175" },
    { "code": "MX", "code3": "MEX", "name": "Mexico", "numeric": "484" },
    { "code": "FM", "code3": "FSM", "name": "Micronesia (Federated States of)", "numeric": "583" },
    { "code": "MD", "code3": "MDA", "name": "Moldova (the Republic of)", "numeric": "498" },
    { "code": "MC", "code3": "MCO", "name": "Monaco", "numeric": "492" },
    { "code": "MN", "code3": "MNG", "name": "Mongolia", "numeric": "496" },
    { "code": "ME", "code3": "MNE", "name": "Montenegro", "numeric": "499" },
    { "code": "MS", "code3": "MSR", "name": "Montserrat", "numeric": "500" },
    { "code": "MA", "code3": "MAR", "name": "Morocco", "numeric": "504" },
    { "code": "MZ", "code3": "MOZ", "name": "Mozambique", "numeric": "508" },
    { "code": "MM", "code3": "MMR", "name": "Myanmar", "numeric": "104" },
    { "code": "NA", "code3": "NAM", "name": "Namibia", "numeric": "516" },
    { "code": "NR", "code3": "NRU", "name": "Nauru", "numeric": "520" },
    { "code": "NP", "code3": "NPL", "name": "Nepal", "numeric": "524" },
    { "code": "NL", "code3": "NLD", "name": "Netherlands", "numeric": "528" },
    { "code": "NC", "code3": "NCL", "name": "New Caledonia", "numeric": "540" },
    { "code": "NZ", "code3": "NZL", "name": "New Zealand", "numeric": "554" },
    { "code": "NI", "code3": "NIC", "name": "Nicaragua", "numeric": "558" },
    { "code": "NE", "code3": "NER", "name": "Niger", "numeric": "562" },
    { "code": "NG", "code3": "NGA", "name": "Nigeria", "numeric": "566" },
    { "code": "NU", "code3": "NIU", "name": "Niue", "numeric": "570" },
    { "code": "NF", "code3": "NFK", "name": "Norfolk Island", "numeric": "574" },
    { "code": "MP", "code3": "MNP", "name": "Northern Mariana Islands", "numeric": "580" },
    { "code": "NO", "code3": "NOR", "name": "Norway", "numeric": "578" },
    { "code": "OM", "code3": "OMN", "name": "Oman", "numeric": "512" },
    { "code": "PK", "code3": "PAK", "name": "Pakistan", "numeric": "586" },
    { "code": "PW", "code3": "PLW", "name": "Palau", "numeric": "585" },
    { "code": "PS", "code3": "PSE", "name": "Palestine, State of", "numeric": "275" },
    { "code": "PA", "code3": "PAN", "name": "Panama", "numeric": "591" },
    { "code": "PG", "code3": "PNG", "name": "Papua New Guinea", "numeric": "598" },
    { "code": "PY", "code3": "PRY", "name": "Paraguay", "numeric": "600" },
    { "code": "PE", "code3": "PER", "name": "Peru", "numeric": "604" },
    { "code": "PH", "code3": "PHL", "name": "Philippines", "numeric": "608" },
    { "code": "PN", "code3": "PCN", "name": "Pitcairn", "numeric": "612" },
    { "code": "PL", "code3": "POL", "name": "Poland", "numeric": "616" },
    { "code": "PT", "code3": "PRT", "name": "Portugal", "numeric": "620" },
    { "code": "PR", "code3": "PRI", "name": "Puerto Rico", "numeric": "630" },
    { "code": "QA", "code3": "QAT", "name": "Qatar", "numeric": "634" },
    { "code": "MK", "code3": "MKD", "name": "Republic of North Macedonia", "numeric": "807" },
    { "code": "RO", "code3": "ROU", "name": "Romania", "numeric": "642" },
    { "code": "RU", "code3": "RUS", "name": "Russian Federation", "numeric": "643" },
    { "code": "RW", "code3": "RWA", "name": "Rwanda", "numeric": "646" },
    { "code": "RE", "code3": "REU", "name": "Réunion", "numeric": "638" },
    { "code": "BL", "code3": "BLM", "name": "Saint Barthélemy", "numeric": "652" },
    { "code": "SH", "code3": "SHN", "name": "Saint Helena, Ascension and Tristan da Cunha", "numeric": "654" },
    { "code": "KN", "code3": "KNA", "name": "Saint Kitts and Nevis", "numeric": "659" },
    { "code": "LC", "code3": "LCA", "name": "Saint Lucia", "numeric": "662" },
    { "code": "MF", "code3": "MAF", "name": "Saint Martin (French part)", "numeric": "663" },
    { "code": "PM", "code3": "SPM", "name": "Saint Pierre and Miquelon", "numeric": "666" },
    { "code": "VC", "code3": "VCT", "name": "Saint Vincent and the Grenadines", "numeric": "670" },
    { "code": "WS", "code3": "WSM", "name": "Samoa", "numeric": "882" },
    { "code": "SM", "code3": "SMR", "name": "San Marino", "numeric": "674" },
    { "code": "ST", "code3": "STP", "name": "Sao Tome and Principe", "numeric": "678" },
    { "code": "SA", "code3": "SAU", "name": "Saudi Arabia", "numeric": "682" },
    { "code": "SN", "code3": "SEN", "name": "Senegal", "numeric": "686" },
    { "code": "RS", "code3": "SRB", "name": "Serbia", "numeric": "688" },
    { "code": "SC", "code3": "SYC", "name": "Seychelles", "numeric": "690" },
    { "code": "SL", "code3": "SLE", "name": "Sierra Leone", "numeric": "694" },
    { "code": "SG", "code3": "SGP", "name": "Singapore", "numeric": "702" },
    { "code": "SX", "code3": "SXM", "name": "Sint Maarten (Dutch part)", "numeric": "534" },
    { "code": "SK", "code3": "SVK", "name": "Slovakia", "numeric": "703" },
    { "code": "SI", "code3": "SVN", "name": "Slovenia", "numeric": "705" },
    { "code": "SB", "code3": "SLB", "name": "Solomon Islands", "numeric": "090" },
    { "code": "SO", "code3": "SOM", "name": "Somalia", "numeric": "706" },
    { "code": "ZA", "code3": "ZAF", "name": "South Africa", "numeric": "710" },
    { "code": "GS", "code3": "SGS", "name": "South Georgia and the South Sandwich Islands", "numeric": "239" },
    { "code": "SS", "code3": "SSD", "name": "South Sudan", "numeric": "728" },
    { "code": "ES", "code3": "ESP", "name": "Spain", "numeric": "724" },
    { "code": "LK", "code3": "LKA", "name": "Sri Lanka", "numeric": "144" },
    { "code": "SD", "code3": "SDN", "name": "Sudan", "numeric": "729" },
    { "code": "SR", "code3": "SUR", "name": "Suriname", "numeric": "740" },
    { "code": "SJ", "code3": "SJM", "name": "Svalbard and Jan Mayen", "numeric": "744" },
    { "code": "SE", "code3": "SWE", "name": "Sweden", "numeric": "752" },
    { "code": "CH", "code3": "CHE", "name": "Switzerland", "numeric": "756" },
    { "code": "SY", "code3": "SYR", "name": "Syrian Arab Republic", "numeric": "760" },
    { "code": "TW", "code3": "TWN", "name": "Taiwan", "numeric": "158" },
    { "code": "TJ", "code3": "TJK", "name": "Tajikistan", "numeric": "762" },
    { "code": "TZ", "code3": "TZA", "name": "Tanzania, United Republic of", "numeric": "834" },
    { "code": "TH", "code3": "THA", "name": "Thailand", "numeric": "764" },
    { "code": "TL", "code3": "TLS", "name": "Timor-Leste", "numeric": "626" },
    { "code": "TG", "code3": "TGO", "name": "Togo", "numeric": "768" },
    { "code": "TK", "code3": "TKL", "name": "Tokelau", "numeric": "772" },
    { "code": "TO", "code3": "TON", "name": "Tonga", "numeric": "776" },
    { "code": "TT", "code3": "TTO", "name": "Trinidad and Tobago", "numeric": "780" },
    { "code": "TN", "code3": "TUN", "name": "Tunisia", "numeric": "788" },
    { "code": "TR", "code3": "TUR", "name": "Turkey", "numeric": "792" },
    { "code": "TM", "code3": "TKM", "name": "Turkmenistan", "numeric": "795" },
    { "code": "TC", "code3": "TCA", "name": "Turks and Caicos Islands", "numeric": "796" },
    { "code": "TV", "code3": "TUV", "name": "Tuvalu", "numeric": "798" },
    { "code": "UG", "code3": "UGA", "name": "Uganda", "numeric": "800" },
    { "code": "UA", "code3": "UKR", "name": "Ukraine", "numeric": "804" },
    { "code": "AE", "code3": "ARE", "name": "United Arab Emirates", "numeric": "784" },
    { "code": "GB", "code3": "GBR", "name": "United Kingdom of Great Britain and Northern Ireland", "numeric": "826" },
    { "code": "UM", "code3": "UMI", "name": "United States Minor Outlying Islands", "numeric": "581" },
    { "code": "US", "code3": "USA", "name": "United States of America", "numeric": "840" },
    { "code": "UY", "code3": "URY", "name": "Uruguay", "numeric": "858" },
    { "code": "UZ", "code3": "UZB", "name": "Uzbekistan", "numeric": "860" },
    { "code": "VU", "code3": "VUT", "name": "Vanuatu", "numeric": "548" },
    { "code": "VE", "code3": "VEN", "name": "Venezuela (Bolivarian Republic of)", "numeric": "862" },
    { "code": "VN", "code3": "VNM", "name": "Viet Nam", "numeric": "704" },
    { "code": "VG", "code3": "VGB", "name": "Virgin Islands (British)", "numeric": "092" },
    { "code": "VI", "code3": "VIR", "name": "Virgin Islands (U.S.)", "numeric": "850" },
    { "code": "WF", "code3": "WLF", "name": "Wallis and Futuna", "numeric": "876" },
    { "code": "EH", "code3": "ESH", "name": "Western Sahara", "numeric": "732" },
    { "code": "YE", "code3": "YEM", "name": "Yemen", "numeric": "887" },
    { "code": "ZM", "code3": "ZMB", "name": "Zambia", "numeric": "894" },
    { "code": "ZW", "code3": "ZWE", "name": "Zimbabwe", "numeric": "716" },
    { "code": "AX", "code3": "ALA", "name": "Åland Islands", "numeric": "248" }
];
export enum Country {
    Afghanistan = 'AF',
    AlandIslands = 'AX',
    Albania = 'AL',
    Algeria = 'DZ',
    AmericanSamoa = 'AS',
    Andorra = 'AD',
    Angola = 'AO',
    Anguilla = 'AI',
    Antarctica = 'AQ',
    AntiguaAndBarbuda = 'AG',
    Argentina = 'AR',
    Armenia = 'AM',
    Aruba = 'AW',
    Australia = 'AU',
    Austria = 'AT',
    Azerbaijan = 'AZ',
    Bahamas = 'BS',
    Bahrain = 'BH',
    Bangladesh = 'BD',
    Barbados = 'BB',
    Belarus = 'BY',
    Belgium = 'BE',
    Belize = 'BZ',
    Benin = 'BJ',
    Bermuda = 'BM',
    Bhutan = 'BT',
    Bolivia = 'BO',
    BonaireSintEustatiusSaba = 'BQ',
    BosniaAndHerzegovina = 'BA',
    Botswana = 'BW',
    BouvetIsland = 'BV',
    Brazil = 'BR',
    BritishIndianOceanTerritory = 'IO',
    BruneiDarussalam = 'BN',
    Bulgaria = 'BG',
    BurkinaFaso = 'BF',
    Burundi = 'BI',
    Cambodia = 'KH',
    Cameroon = 'CM',
    Canada = 'CA',
    CapeVerde = 'CV',
    CaymanIslands = 'KY',
    CentralAfricanRepublic = 'CF',
    Chad = 'TD',
    Chile = 'CL',
    China = 'CN',
    ChristmasIsland = 'CX',
    CocosKeelingIslands = 'CC',
    Colombia = 'CO',
    Comoros = 'KM',
    Congo = 'CG',
    CongoDemocraticRepublic = 'CD',
    CookIslands = 'CK',
    CostaRica = 'CR',
    CoteDIvoire = 'CI',
    Croatia = 'HR',
    Cuba = 'CU',
    Curaçao = 'CW',
    Cyprus = 'CY',
    CzechRepublic = 'CZ',
    Denmark = 'DK',
    Djibouti = 'DJ',
    Dominica = 'DM',
    DominicanRepublic = 'DO',
    Ecuador = 'EC',
    Egypt = 'EG',
    ElSalvador = 'SV',
    EquatorialGuinea = 'GQ',
    Eritrea = 'ER',
    Estonia = 'EE',
    Ethiopia = 'ET',
    FalklandIslands = 'FK',
    FaroeIslands = 'FO',
    Fiji = 'FJ',
    Finland = 'FI',
    France = 'FR',
    FrenchGuiana = 'GF',
    FrenchPolynesia = 'PF',
    FrenchSouthernTerritories = 'TF',
    Gabon = 'GA',
    Gambia = 'GM',
    Georgia = 'GE',
    Germany = 'DE',
    Ghana = 'GH',
    Gibraltar = 'GI',
    Greece = 'GR',
    Greenland = 'GL',
    Grenada = 'GD',
    Guadeloupe = 'GP',
    Guam = 'GU',
    Guatemala = 'GT',
    Guernsey = 'GG',
    Guinea = 'GN',
    GuineaBissau = 'GW',
    Guyana = 'GY',
    Haiti = 'HT',
    HeardIslandMcdonaldIslands = 'HM',
    HolySeeVaticanCityState = 'VA',
    Honduras = 'HN',
    HongKong = 'HK',
    Hungary = 'HU',
    Iceland = 'IS',
    India = 'IN',
    Indonesia = 'ID',
    Iran = 'IR',
    Iraq = 'IQ',
    Ireland = 'IE',
    IsleOfMan = 'IM',
    Israel = 'IL',
    Italy = 'IT',
    Jamaica = 'JM',
    Japan = 'JP',
    Jersey = 'JE',
    Jordan = 'JO',
    Kazakhstan = 'KZ',
    Kenya = 'KE',
    Kiribati = 'KI',
    Korea = 'KR',
    KoreaDemocraticPeoplesRepublic = 'KP',
    Kuwait = 'KW',
    Kyrgyzstan = 'KG',
    LaoPeoplesDemocraticRepublic = 'LA',
    Latvia = 'LV',
    Lebanon = 'LB',
    Lesotho = 'LS',
    Liberia = 'LR',
    LibyanArabJamahiriya = 'LY',
    Liechtenstein = 'LI',
    Lithuania = 'LT',
    Luxembourg = 'LU',
    Macao = 'MO',
    Macedonia = 'MK',
    Madagascar = 'MG',
    Malawi = 'MW',
    Malaysia = 'MY',
    Maldives = 'MV',
    Mali = 'ML',
    Malta = 'MT',
    MarshallIslands = 'MH',
    Martinique = 'MQ',
    Mauritania = 'MR',
    Mauritius = 'MU',
    Mayotte = 'YT',
    Mexico = 'MX',
    Micronesia = 'FM',
    Moldova = 'MD',
    Monaco = 'MC',
    Mongolia = 'MN',
    Montenegro = 'ME',
    Montserrat = 'MS',
    Morocco = 'MA',
    Mozambique = 'MZ',
    Myanmar = 'MM',
    Namibia = 'NA',
    Nauru = 'NR',
    Nepal = 'NP',
    Netherlands = 'NL',
    NewCaledonia = 'NC',
    NewZealand = 'NZ',
    Nicaragua = 'NI',
    Niger = 'NE',
    Nigeria = 'NG',
    Niue = 'NU',
    NorfolkIsland = 'NF',
    NorthernMarianaIslands = 'MP',
    Norway = 'NO',
    Oman = 'OM',
    Pakistan = 'PK',
    Palau = 'PW',
    PalestinianTerritory = 'PS',
    Panama = 'PA',
    PapuaNewGuinea = 'PG',
    Paraguay = 'PY',
    Peru = 'PE',
    Philippines = 'PH',
    Pitcairn = 'PN',
    Poland = 'PL',
    Portugal = 'PT',
    PuertoRico = 'PR',
    Qatar = 'QA',
    Reunion = 'RE',
    Romania = 'RO',
    RussianFederation = 'RU',
    Rwanda = 'RW',
    SaintBarthelemy = 'BL',
    SaintHelena = 'SH',
    SaintKittsAndNevis = 'KN',
    SaintLucia = 'LC',
    SaintMartin = 'MF',
    SaintPierreAndMiquelon = 'PM',
    SaintVincentAndGrenadines = 'VC',
    Samoa = 'WS',
    SanMarino = 'SM',
    SaoTomeAndPrincipe = 'ST',
    SaudiArabia = 'SA',
    Senegal = 'SN',
    Serbia = 'RS',
    Seychelles = 'SC',
    SierraLeone = 'SL',
    Singapore = 'SG',
    SintMaarten = 'SX',
    Slovakia = 'SK',
    Slovenia = 'SI',
    SolomonIslands = 'SB',
    Somalia = 'SO',
    SouthAfrica = 'ZA',
    SouthGeorgiaAndSandwichIsl = 'GS',
    SouthSudan = 'SS',
    Spain = 'ES',
    SriLanka = 'LK',
    Sudan = 'SD',
    Suriname = 'SR',
    SvalbardAndJanMayen = 'SJ',
    Swaziland = 'SZ',
    Sweden = 'SE',
    Switzerland = 'CH',
    SyrianArabRepublic = 'SY',
    Taiwan = 'TW',
    Tajikistan = 'TJ',
    Tanzania = 'TZ',
    Thailand = 'TH',
    TimorLeste = 'TL',
    Togo = 'TG',
    Tokelau = 'TK',
    Tonga = 'TO',
    TrinidadAndTobago = 'TT',
    Tunisia = 'TN',
    Turkey = 'TR',
    Turkmenistan = 'TM',
    TurksAndCaicosIslands = 'TC',
    Tuvalu = 'TV',
    Uganda = 'UG',
    Ukraine = 'UA',
    UnitedArabEmirates = 'AE',
    UnitedKingdom = 'GB',
    UnitedStates = 'US',
    UnitedStatesOutlyingIslands = 'UM',
    Uruguay = 'UY',
    Uzbekistan = 'UZ',
    Vanuatu = 'VU',
    Venezuela = 'VE',
    Vietnam = 'VN',
    VirginIslandsBritish = 'VG',
    VirginIslandsUS = 'VI',
    WallisAndFutuna = 'WF',
    WesternSahara = 'EH',
    Yemen = 'YE',
    Zambia = 'ZM',
    Zimbabwe = 'ZW',
}
