export const philippinesRegions = [
  { regionCode: 'r01', name: 'Region I (Ilocos Region)' },
  { regionCode: 'r02', name: 'Region II (Cagayan Valley)' },
  { regionCode: 'r03', name: 'Region III (Central Luzon)' },
  { regionCode: 'r04a', name: 'Region IV-A (Calabarzon)' },
  { regionCode: 'r04b', name: 'Region IV-B (Mimaropa)' },
  { regionCode: 'r05', name: 'Region V (Bicol Region)' },
  { regionCode: 'r06', name: 'Region VI (Western Visayas)' },
  { regionCode: 'r07', name: 'Region VII (Central Visayas)' },
  { regionCode: 'r08', name: 'Region VIII (Eastern Visayas)' },
  { regionCode: 'r09', name: 'Region IX (Zamboanga Peninsula)' },
  { regionCode: 'r10', name: 'Region X (Northern Mindanao)' },
  { regionCode: 'r11', name: 'Region XI (Davao Region)' },
  { regionCode: 'r12', name: 'Region XII (Soccsksargen)' },
  { regionCode: 'r13', name: 'Region XIII (Caraga)' },
  { regionCode: 'car', name: 'Cordillera Administrative Region' },
  { regionCode: 'armm', name: 'Autonomous Region in Muslim Mindanao' },
  { regionCode: 'ncr', name: 'National Capital Region' },
]
